routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index')->name('home');

Auth::routes();

Route::group(['prefix' => 'user'], function(){
Route::get('/user/logout', 'Auth\LoginController@logoutUser')->name('user.logout');
Route::get('/', 'DashboardController@index')->name('home');
Route::resource('dashboard', 'DashboardController');
Route::resource('manageclass', 'ClassroomController');
Route::resource('manageteacher', 'TeacherController');
Route::resource('managestudent', 'StudentController');
Route::resource('managelist', 'ListController');
Route::get('pdf/{id}', 'ListController@pdf')->name('pdf');
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $table = 'tbl_student';
    protected $primaryKey = 'id_student';
    protected $fillable = [
        'nama_student',
        'id_class',
    ];

    public function classroom()
    {
        return $this->belongsTo('App\Classroom','id_class');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Classroom;
use App\Student;

use Redirect;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $page = 'pagestudent';
        $student = Student::paginate(10);
        return view('backend.student.manage_student', compact('page','student'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page = 'pagestudent';
        $class = Classroom::all();
        $student = Student::all();
        return view('backend.student.add_student', compact('page','student','class'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'nama_student' => 'required|string|max:100',
            'id_class' => 'required',
        ]);
        $student = $request->except('_token');
        try {
             Student::insert($student); 
        } catch (Exception $e) {
                    return Redirect::route('managestudent.index');
        }
        return Redirect::route('managestudent.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $page = 'pagestudent';
        $student = Student::all();
        $student = Student::find($id);
        return view('backend.student.show_student', compact('page','student'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page = 'pagestudent';
        $class = Classroom::all();
        $student = Student::all();
        $student = Student::find($id);

        return view('backend.student.edit_student', compact('page','student','class'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'nama_student' => 'required|string|max:100',
            'id_class' => 'required',
        ]);
        $student = $request->except('_token','_method');
        try {
             Student::where('id_student', $id)->update($student);
        } catch (Exception $e) {
                    return Redirect::route('managestudent.index');
        }
        return Redirect::route('managestudent.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Student::where('id_student',$id)->delete();
        return Redirect::route('managestudent.index');
    }
}

resources/views/backend/student/add_student.blade.php
@extends('layoutbackend.main_content')

@section('page_content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
         Input Data Student
      </h1>
      <ol class="breadcrumb breadcrumb-col-pink">
        <li><a href="#"><i class="material-icons">home</i> Dashboard</a></li>
        <li><a href="#"><i class="material-icons">person</i> Student</a></li>
        <li class="active"><i class="material-icons">add</i> Add Student</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
      <div class="container-fluid">

        <!-- Basic Validation -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>Add New Student</h2>                         
                        </div>
                        @if ($errors->any())
                      <div class="alert alert-danger">
                        <ul>
                   @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                          @endforeach
                        </ul>
                      </div>
                    @endif <!-- /.form validation -->
                        <div class="body">
                            <form id="form_validation" files="true" method="post" action="{{ route('managestudent.store') }}" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control" name="nama_student" required>
                                        <label class="form-label">Student Name</label>
                                    </div>&nbsp;
                                    <div class="row clearfix">
                                      <div class="col-sm-6">
                                          <select class="form-control show-tick" name="id_class" id="id_class">
                                              <option value="">-- Select Classroom --</option>
                                              @foreach ($class as $classes)
                                              <option value="{{ $classes->id_class }}">{{ $classes->nama_class }}</option>
                                               @endforeach 
                                          </select>
                                      </div>
                                    </div>
                                </div>
                                 <a href="{{ route('managestudent.index') }}" class="btn btn-warning">&nbsp; BACK</a>
                                <button class="btn btn-primary waves-effect" type="submit">SUBMIT</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
      </div>
    </section>
    <!-- /.content -->
@stop

resources/views/backend/student/edit_student.blade.php
@extends('layoutbackend.main_content')

@section('page_content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
         Edit Data Student
      </h1>
      <ol class="breadcrumb breadcrumb-col-pink">
        <li><a href="#"><i class="material-icons">home</i> Dashboard</a></li>
        <li><a href="#"><i class="material-icons">person</i> Student</a></li>
        <li class="active"><i class="material-icons">edit</i> Edit Student</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
      <div class="container-fluid">

        <!-- Basic Validation -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>Edit Student</h2>                         
                        </div>
                        @if ($errors->any())
                      <div class="alert alert-danger">
                        <ul>
                          @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                          @endforeach
                        </ul>
                      </div>
                    @endif <!-- /.form validation -->
                        <div class="body">
                            <form id="form_validation" files="true" method="post" action="{{ route('managestudent.update', $student->id_student) }}" enctype="multipart/form-data">
                                 @csrf {{ method_field('PATCH')}}
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control" id="nama_student" name="nama_student" value="{{$student->nama_student}}">
                                        <label class="form-label">Student Name</label>
                                    </div>
                                </div>&nbsp;
                                    <div class="row clearfix">
                                      <div class="col-sm-6">
                                          <select class="form-control show-tick" name="id_class" id="id_class">
                                              <option value="">-- Select Classroom --</option>
                                              @foreach ($class as $classes)
                                              <option value="{{ $classes->id_class }}">{{ $classes->nama_class }}</option>
                                               @endforeach 
                                          </select>
                                      </div>
                                    </div>
                                 <a href="{{ route('managestudent.index') }}" class="btn btn-warning">&nbsp; BACK</a>
                                <button class="btn btn-primary waves-effect" type="submit">UPDATE</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
      </div>

    </section>
    <!-- /.content -->
@stop

resources/views/backend/student/manage_student.blade.php
@extends('layoutbackend.main_content')

@section('page_content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
         Student
      </h1>
      <ol class="breadcrumb breadcrumb-col-pink">
        <li><a href="#"><i class="material-icons">home</i> Dashboard</a></li>
        <li class="active"><i class="material-icons">person</i> Student</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
      <div class="container-fluid">

        <div class="row clearfix">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <div class="card">
                <div class="body">
                    <h4>Welcome AdminStaff!</h4>
                </div>
              </div>
          </div>
        </div>


       <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Table Student
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li>
                                    <a class="btn btn-primary"  href="{{ route('managestudent.create') }}"><i class="fa fa-plus-circle"></i>&nbsp; Add Student</a>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                          <th>Class Name</th>
                                            <th>Student Name</th>
                                            <th colspan="3">Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                          <th>Class Name</th>
                                            <th>Student Name</th>
                                            <th colspan="3">Action</th>                                
                                        </tr>
                                    </tfoot>
                                    @foreach ($student as $students)
                                    <tbody>
                                        <tr>
                                          <td>{{$students->classroom->nama_class}}</td>
                                            <td>{{$students->nama_student}}</td>
                                           <td>
                                          <form  method="post" action="{{ route('managestudent.destroy', $students->id_student) }}">
                                              {{ csrf_field()}} {{ method_field('DELETE') }}
                                              <a class="btn btn-info" href="{{ route('managestudent.show', $students->id_student) }}"><i class="material-icons">visibility</i></a>
                                              <a class="btn btn-warning"  href="{{ route('managestudent.edit', $students->id_student) }}"><i class="material-icons">edit</i></a>
                                              <button type="submit" class="btn btn-danger"><i class="material-icons">delete</i></button>
                                          </form>
                                        </td>
                                        </tr>
                                    </tbody>
                                    @endforeach
                                </table>
                            </div>
                            <div class="box-footer ">
                            <div class="text-center">
                                  {!! $student->links(); !!}
                            </div>
                          </div> 
                        </div>
                    </div>
                </div>
            </div>

      </div>
    </section>
    <!-- /.content -->
@stop

resources/views/backend/student/show_student.blade.php
@extends('layoutbackend.main_content')

@section('page_content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
         Show Data Student
      </h1>
      <ol class="breadcrumb breadcrumb-col-pink">
        <li><a href="#"><i class="material-icons">home</i> Dashboard</a></li>
        <li><a href="#"><i class="material-icons">person</i> Student</a></li>
        <li class="active"><i class="material-icons">visibility</i> Show Student</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
      <div class="container-fluid">

        <!-- Basic Validation -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>Show Student</h2>                         
                        </div>
                        @if ($errors->any())
                      <div class="alert alert-danger">
                        <ul>
                          @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                          @endforeach
                        </ul>
                      </div>
                    @endif <!-- /.form validation -->
                        <div class="body">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control" id="nama_student" name="nama_student" value="{{$student->nama_student}}" disabled="">
                                        <label class="form-label">Student Name</label>
                                    </div>
                                </div>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control" id="nama_class" name="nama_class" value="{{$student->classroom->nama_class}}" disabled="">
                                        <label class="form-label">Class Name</label>
                                    </div>
                                </div>
                                 <a href="{{ route('managestudent.index') }}" class="btn btn-warning">&nbsp; BACK</a>
                        </div>
                    </div>
                </div>
            </div>
      </div>
    </section>
    <!-- /.content -->
@stop