routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index')->name('home');

Auth::routes();

Route::group(['prefix' => 'user'], function(){
Route::get('/user/logout', 'Auth\LoginController@logoutUser')->name('user.logout');
Route::get('/', 'DashboardController@index')->name('home');
Route::resource('dashboard', 'DashboardController');
Route::resource('manageclass', 'ClassroomController');
Route::resource('manageteacher', 'TeacherController');
Route::resource('managestudent', 'StudentController');
Route::resource('managelist', 'ListController');
Route::get('pdf/{id}', 'ListController@pdf')->name('pdf');
});

resources/views/backend/class/add_class.blade.php
@extends('layoutbackend.main_content')

@section('page_content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Input Data StudentClass
    </h1>
    <ol class="breadcrumb breadcrumb-col-pink">
        <li><a href="#"><i class="material-icons">home</i> Dashboard</a></li>
        <li><a href="#"><i class="material-icons">class</i> Classroom</a></li>
        <li class="active"><i class="material-icons">add</i> Add Classroom</li>
    </ol>
</section>

<!-- Main content -->
<section class="content-header">
  <div class="container-fluid">

<!-- Basic Validation -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>Add New Classroom</h2>                         
                </div>
                @if ($errors->any())
                  <div class="alert alert-danger">
                    <ul>
                      @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                      @endforeach
                    </ul>
                  </div>
                @endif <!-- /.form validation -->
                <div class="body">
                    <form id="form_validation" files="true" method="post" action="{{ route('manageclass.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" class="form-control" name="nama_class" required>
                                <label class="form-label">Class Name</label>
                            </div>
                        </div>
                        <a href="{{ route('manageclass.index') }}" class="btn btn-warning">&nbsp; BACK</a>
                        <button class="btn btn-primary waves-effect" type="submit">SUBMIT</button>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </div>
</section>
<!-- /.content -->
@stop

resources/views/backend/class/edit_class.blade.php
@extends('layoutbackend.main_content')

@section('page_content')

<!-- Content Header (Page header) -->
<section class="content-header">
      <h1>
         Edit Data Class
      </h1>
      <ol class="breadcrumb breadcrumb-col-pink">
        <li><a href="#"><i class="material-icons">home</i> Dashboard</a></li>
        <li><a href="#"><i class="material-icons">class</i> Classroom</a></li>
        <li class="active"><i class="material-icons">edit</i> Edit Class</li>
      </ol>
</section>

<!-- Main content -->
<section class="content-header">
      <div class="container-fluid">

        <!-- Basic Validation -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>Edit Class</h2>                         
                        </div>
                        @if ($errors->any())
                      <div class="alert alert-danger">
                        <ul>
                          @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                          @endforeach
                        </ul>
                      </div>
                    @endif <!-- /.form validation -->
                        <div class="body">
                            <form id="form_validation" files="true" method="post" action="{{ route('manageclass.update', $class->id_class) }}" enctype="multipart/form-data">
                                 @csrf {{ method_field('PATCH')}}
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control" id="nama_class" name="nama_class" value="{{$class->nama_class}}">
                                        <label class="form-label">Class Name</label>
                                    </div>
                                </div>
                                 <a href="{{ route('manageclass.index') }}" class="btn btn-warning">&nbsp; BACK</a>
                                <button class="btn btn-primary waves-effect" type="submit">UPDATE</button>
                          </form>
                      </div>
                </div>
            </div>
        </div>
  </div>

</section>
<!-- /.content -->
@stop

resources/views/backend/class/manage_class.blade.php
@extends('layoutbackend.main_content')

@section('page_content')

<!-- Content Header (Page header) -->
<section class="content-header">
      <h1>
         Class
      </h1>
      <ol class="breadcrumb breadcrumb-col-pink">
        <li><a href="#"><i class="material-icons">home</i> Dashboard</a></li>
        <li class="active"><i class="material-icons">class</i> Classroom</li>
      </ol>
</section>

<!-- Main content -->
<section class="content-header">
    <div class="container-fluid">

      <div class="row clearfix">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="card">
              <div class="body">
                   <h4>Welcome AdminStaff!</h4>
              </div>
            </div>
        </div>
      </div>
       <div class="row clearfix">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <div class="card">
                  <div class="header">
                      <h2>
                          Table Class
                      </h2>
                      <ul class="header-dropdown m-r--5">
                          <li>
                              <a class="btn btn-primary"  href="{{ route('manageclass.create') }}"><i class="fa fa-plus-circle"></i>&nbsp; Add Class</a>
                          </li>
                      </ul>
                   </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                            <th>Class Name</th>
                                            <th colspan="3">Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Class Name</th>
                                            <th colspan="3">Action</th>                                
                                        </tr>
                                    </tfoot>
                                    @foreach ($class as $classes)
                                    <tbody>
                                        <tr>
                                            <td>{{$classes->nama_class}}</td>

                                           <td>
                                          <form  method="post" action="{{ route('manageclass.destroy', $classes->id_class) }}">
                                              {{ csrf_field()}} {{ method_field('DELETE') }}
                                              <a class="btn btn-info" href="{{ route('manageclass.show', $classes->id_class) }}"><i class="material-icons">visibility</i></a>
                                              <a class="btn btn-warning"  href="{{ route('manageclass.edit', $classes->id_class) }}"><i class="material-icons">edit</i></a>
                                              <button type="submit" class="btn btn-danger"><i class="material-icons">delete</i></button>
                                          </form>
                                        </td>
                                        </tr>
                                    </tbody>
                                    @endforeach
                                </table>
                            </div>
                            <div class="box-footer ">
                            <div class="text-center">
                                  {!! $class->links(); !!}
                            </div>
                          </div> 
                        </div>
                    </div>
                </div>
            </div>

      </div>
</section>
<!-- /.content -->
@stop

resources/views/backend/class/show_class.blade.php
@extends('layoutbackend.main_content')

@section('page_content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
         Show Data Class
      </h1>
      <ol class="breadcrumb breadcrumb-col-pink">
        <li><a href="#"><i class="material-icons">home</i> Dashboard</a></li>
        <li><a href="#"><i class="material-icons">class</i> Classroom</a></li>
        <li class="active"><i class="material-icons">visibility</i> Show Class</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
      <div class="container-fluid">

        <!-- Basic Validation -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>Show Class</h2>                         
                        </div>
                        @if ($errors->any())
                      <div class="alert alert-danger">
                        <ul>
                          @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                          @endforeach
                        </ul>
                      </div>
                    @endif <!-- /.form validation -->
                        <div class="body">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control" id="nama_class" name="nama_class" value="{{$class->nama_class}}" disabled="">
                                        <label class="form-label">Class Name</label>
                                    </div>&nbsp;
                                </div>
                                 <a href="{{ route('manageclass.index') }}" class="btn btn-warning">&nbsp; BACK</a>
                        </div>
                    </div>
                </div>
            </div>
      </div>
    </section>
    <!-- /.content -->
@stop