routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index')->name('home');

Auth::routes();

Route::group(['prefix' => 'user'], function(){
Route::get('/user/logout', 'Auth\LoginController@logoutUser')->name('user.logout');
Route::get('/', 'DashboardController@index')->name('home');
Route::resource('dashboard', 'DashboardController');
Route::resource('manageclass', 'ClassroomController');
Route::resource('manageteacher', 'TeacherController');
Route::resource('managestudent', 'StudentController');
Route::resource('managelist', 'ListController');
Route::get('pdf/{id}', 'ListController@pdf')->name('pdf');
});

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $table = 'tbl_teacher';
    protected $primaryKey = 'id_teacher';
    protected $fillable = [
        'nama_teacher',
        'id_class',
    ];

    public function classroom()
    {
        return $this->belongsTo('App\Classroom','id_class');
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Teacher;
use App\Classroom;

use Redirect;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $page = 'pageteacher';
        $teacher = Teacher::paginate(10);
        return view('backend.teacher.manage_teacher', compact('page','teacher'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page = 'pageteacher';
        $class = Classroom::all();
        $teacher = Teacher::all();
        return view('backend.teacher.add_teacher', compact('page','teacher','class'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'nama_teacher' => 'required|string|max:100',
            'id_class' => 'required',
        ]);
        $teacher = $request->except('_token');
        try {
             Teacher::insert($teacher); 
        } catch (Exception $e) {
                    return Redirect::route('manageteacher.index');
        }
        return Redirect::route('manageteacher.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $page = 'pageteacher';
        $teacher = Teacher::all();
        $teacher = Teacher::find($id);
        return view('backend.teacher.show_teacher', compact('page','teacher'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page = 'pageteacher';
        $class = Classroom::all();
        $teacher = Teacher::all();
        $teacher = Teacher::find($id);

        return view('backend.teacher.edit_teacher', compact('page','teacher','class'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'nama_teacher' => 'required|string|max:100',
            'id_class' => 'required',
        ]);
        $teacher = $request->except('_token','_method');
        try {
             Teacher::where('id_teacher', $id)->update($teacher);
        } catch (Exception $e) {
                    return Redirect::route('manageteacher.index');
        }
        return Redirect::route('manageteacher.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Teacher::where('id_teacher',$id)->delete();
        return Redirect::route('manageteacher.index');
    }
}

resources/views/backend/teacher/add_teacher.blade.php
@extends('layoutbackend.main_content')

@section('page_content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
         Input Data Teacher
      </h1>
      <ol class="breadcrumb breadcrumb-col-pink">
        <li><a href="#"><i class="material-icons">home</i> Dashboard</a></li>
        <li><a href="#"><i class="material-icons">assignment</i> Teacher</a></li>
        <li class="active"><i class="material-icons">add</i> Add Teacher</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
      <div class="container-fluid">

        <!-- Basic Validation -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>Add New Teacher</h2>                         
                        </div>
                    @if ($errors->any())
                      <div class="alert alert-danger">
                        <ul>
                          @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                          @endforeach
                        </ul>
                      </div>
                    @endif <!-- /.form validation -->
                        <div class="body">
                            <form id="form_validation" files="true" method="post" action="{{ route('manageteacher.store') }}" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control" name="nama_teacher" required>
                                        <label class="form-label">Teacher Name</label>
                                    </div>
                                </div>&nbsp;
                                    <div class="row clearfix">
                                      <div class="col-sm-6">
                                          <select class="form-control show-tick" name="id_class" id="id_class">
                                              <option value="">-- Select Classroom --</option>
                                              @foreach ($class as $classes)
                                              <option value="{{ $classes->id_class }}">{{ $classes->nama_class }}</option>
                                               @endforeach 
                                          </select>
                                      </div>
                                    </div>
                                 <a href="{{ route('manageteacher.index') }}" class="btn btn-warning">&nbsp; BACK</a>
                                <button class="btn btn-primary waves-effect" type="submit">SUBMIT</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
      </div>
    </section>
    <!-- /.content -->
@stop

resources/views/backend/teacher/edit_teacher.blade.php
@extends('layoutbackend.main_content')

@section('page_content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
         Edit Data Teacher
      </h1>
      <ol class="breadcrumb breadcrumb-col-pink">
        <li><a href="#"><i class="material-icons">home</i> Dashboard</a></li>
        <li><a href="#"><i class="material-icons">assignment</i> Teacher</a></li>
        <li class="active"><i class="material-icons">edit</i> Edit Teacher</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
      <div class="container-fluid">

        <!-- Basic Validation -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>Edit Teacher</h2>                         
                        </div>
                        @if ($errors->any())
                      <div class="alert alert-danger">
                        <ul>
                          @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                          @endforeach
                        </ul>
                      </div>
                    @endif <!-- /.form validation -->
                        <div class="body">
                            <form id="form_validation" files="true" method="post" action="{{ route('manageteacher.update', $teacher->id_teacher) }}" enctype="multipart/form-data">
                                 @csrf {{ method_field('PATCH')}}
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control" id="nama_teacher" name="nama_teacher" value="{{$teacher->nama_teacher}}">
                                        <label class="form-label">Teacher Name</label>
                                    </div>
                                </div>&nbsp;
                                    <div class="row clearfix">
                                      <div class="col-sm-6">
                                          <select class="form-control show-tick" name="id_class" id="id_class">
                                              <option value="">-- Select Classroom --</option>
                                              @foreach ($class as $classes)
                                              <option value="{{ $classes->id_class }}">{{ $classes->nama_class }}</option>
                                               @endforeach 
                                          </select>
                                      </div>
                                    </div>
                                 <a href="{{ route('manageteacher.index') }}" class="btn btn-warning">&nbsp; BACK</a>
                                <button class="btn btn-primary waves-effect" type="submit">UPDATE</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
      </div>

    </section>
    <!-- /.content -->
@stop

resources/views/backend/teacher/manage_teacher.blade.php
@extends('layoutbackend.main_content')

@section('page_content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
         Teacher
      </h1>
      <ol class="breadcrumb breadcrumb-col-pink">
        <li><a href="#"><i class="material-icons">home</i> Dashboard</a></li>
        <li class="active"><i class="material-icons">assignment</i> Teacher</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
      <div class="container-fluid">

        <div class="row clearfix">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <div class="card">
                <div class="body">
                    <h4>Welcome AdminStaff!</h4>
                </div>
              </div>
          </div>
        </div>


       <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Table Teacher
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li>
                                    <a class="btn btn-primary"  href="{{ route('manageteacher.create') }}"><i class="fa fa-plus-circle"></i>&nbsp; Add Teacher</a>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                          <th>Class Name</th>
                                            <th>Teacher Name</th>
                                            <th colspan="3">Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                           <th>Class Name</th>
                                            <th>Teacher Name</th>
                                            <th colspan="3">Action</th>                                
                                        </tr>
                                    </tfoot>
                                    @foreach ($teacher as $teachers)
                                    <tbody>
                                        <tr>
                                            <td>{{$teachers->classroom->nama_class}}</td>
                                            <td>{{$teachers->nama_teacher}}</td>
                                           <td>
                                          <form  method="post" action="{{ route('manageteacher.destroy', $teachers->id_teacher) }}">
                                              {{ csrf_field()}} {{ method_field('DELETE') }}
                                              <a class="btn btn-info" href="{{ route('manageteacher.show', $teachers->id_teacher) }}"><i class="material-icons">visibility</i></a>
                                              <a class="btn btn-warning"  href="{{ route('manageteacher.edit', $teachers->id_teacher) }}"><i class="material-icons">edit</i></a>
                                              <button type="submit" class="btn btn-danger"><i class="material-icons">delete</i></button>
                                          </form>
                                        </td>
                                        </tr>
                                    </tbody>
                                    @endforeach
                                </table>
                            </div>
                            <div class="box-footer ">
                            <div class="text-center">
                                  {!! $teacher->links(); !!}
                            </div>
                          </div> 
                        </div>
                    </div>
                </div>
            </div>

      </div>
    </section>
    <!-- /.content -->
@stop

resources/views/backend/teacher/show_teacher.blade.php
@extends('layoutbackend.main_content')

@section('page_content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
         Show Data Teacher
      </h1>
      <ol class="breadcrumb breadcrumb-col-pink">
        <li><a href="#"><i class="material-icons">home</i> Dashboard</a></li>
        <li><a href="#"><i class="material-icons">assignment</i> Teacher</a></li>
        <li class="active"><i class="material-icons">visibility</i> Show Teacher</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content-header">
      <div class="container-fluid">

        <!-- Basic Validation -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>Show Teacher</h2>                         
                        </div>
                        @if ($errors->any())
                      <div class="alert alert-danger">
                        <ul>
                          @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                          @endforeach
                        </ul>
                      </div>
                    @endif <!-- /.form validation -->
                        <div class="body">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control" id="nama_teacher" name="nama_teacher" value="{{$teacher->nama_teacher}}" disabled="">
                                        <label class="form-label">Teacher Name</label>
                                    </div> 
                                </div>
                                 <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control" id="nama_class" name="nama_class" value="{{$teacher->classroom->nama_class}}" disabled="">
                                        <label class="form-label">Class Name</label>
                                    </div> 
                                </div>
                                 <a href="{{ route('manageteacher.index') }}" class="btn btn-warning">&nbsp; BACK</a>
                        </div>
                    </div>
                </div>
            </div>
      </div>
    </section>
    <!-- /.content -->
@stop